// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdhZVWgiwhchiuukS9o462B-JiAyJtj3I',
    appId: '1:323582705102:web:e4f1086d8ee97cd8db3f9f',
    messagingSenderId: '323582705102',
    projectId: 'bike-app-iot',
    authDomain: 'bike-app-iot.firebaseapp.com',
    storageBucket: 'bike-app-iot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBvJSe5D26tB5LpEh-7koRCe-_x-YL4_M',
    appId: '1:323582705102:android:025e8b0790268276db3f9f',
    messagingSenderId: '323582705102',
    projectId: 'bike-app-iot',
    storageBucket: 'bike-app-iot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC92GVBqSDBFVi1W_uGuIBLfvnkj51gPXc',
    appId: '1:323582705102:ios:2fe64fdc4c9d8af0db3f9f',
    messagingSenderId: '323582705102',
    projectId: 'bike-app-iot',
    storageBucket: 'bike-app-iot.appspot.com',
    iosClientId: '323582705102-pvfd4jur8lfqfl8a6ebqeuheks65v0vs.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC92GVBqSDBFVi1W_uGuIBLfvnkj51gPXc',
    appId: '1:323582705102:ios:a2829d4399ebc0f5db3f9f',
    messagingSenderId: '323582705102',
    projectId: 'bike-app-iot',
    storageBucket: 'bike-app-iot.appspot.com',
    iosClientId: '323582705102-grlmsvdfpnde1mbqset39tjd58qskf9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignup.RunnerTests',
  );
}
